export interface RecommenderRow {
  userId: number;

  rec1: string | null;
  rec2: string | null;
  rec3: string | null;
  rec4: string | null;
  rec5: string | null;
  rec6: string | null;
  rec7: string | null;
  rec8: string | null;
  rec9: string | null;
  rec10: string | null;
  rec11: string | null;
  rec12: string | null;
  rec13: string | null;
  rec14: string | null;
  rec15: string | null;
  rec16: string | null;
  rec17: string | null;
  rec18: string | null;
  rec19: string | null;
  rec20: string | null;

  tvRec1: string | null;
  tvRec2: string | null;
  tvRec3: string | null;
  tvRec4: string | null;
  tvRec5: string | null;
  tvRec6: string | null;
  tvRec7: string | null;
  tvRec8: string | null;
  tvRec9: string | null;
  tvRec10: string | null;
  tvRec11: string | null;
  tvRec12: string | null;
  tvRec13: string | null;
  tvRec14: string | null;
  tvRec15: string | null;
  tvRec16: string | null;
  tvRec17: string | null;
  tvRec18: string | null;
  tvRec19: string | null;
  tvRec20: string | null;

  movieRec1: string | null;
  movieRec2: string | null;
  movieRec3: string | null;
  movieRec4: string | null;
  movieRec5: string | null;
  movieRec6: string | null;
  movieRec7: string | null;
  movieRec8: string | null;
  movieRec9: string | null;
  movieRec10: string | null;
  movieRec11: string | null;
  movieRec12: string | null;
  movieRec13: string | null;
  movieRec14: string | null;
  movieRec15: string | null;
  movieRec16: string | null;
  movieRec17: string | null;
  movieRec18: string | null;
  movieRec19: string | null;
  movieRec20: string | null;

  nicheRec1: string | null;
  nicheRec2: string | null;
  nicheRec3: string | null;
  nicheRec4: string | null;
  nicheRec5: string | null;
  nicheRec6: string | null;
  nicheRec7: string | null;
  nicheRec8: string | null;
  nicheRec9: string | null;
  nicheRec10: string | null;
  nicheRec11: string | null;
  nicheRec12: string | null;
  nicheRec13: string | null;
  nicheRec14: string | null;
  nicheRec15: string | null;
  nicheRec16: string | null;
  nicheRec17: string | null;
  nicheRec18: string | null;
  nicheRec19: string | null;
  nicheRec20: string | null;
}

  